"""Fase 2 — Foundation: copia scaffold Next.js, popula globals.css com tokens, baixa assets."""
from __future__ import annotations

import logging
import re
import shutil
from pathlib import Path

from .nextjs_utils import has_node, run_npm_install

logger = logging.getLogger(__name__)


def _rgb_to_hsl_str(color: str) -> str | None:
    """Converte rgb(r, g, b) ou rgba(r, g, b, a) pra '<h> <s>% <l>%' (formato CSS HSL Tailwind)."""
    m = re.match(r"rgba?\((\d+),\s*(\d+),\s*(\d+)", color)
    if not m:
        return None
    r, g, b = int(m.group(1)) / 255, int(m.group(2)) / 255, int(m.group(3)) / 255
    mx, mn = max(r, g, b), min(r, g, b)
    l = (mx + mn) / 2
    if mx == mn:
        h = s = 0.0
    else:
        d = mx - mn
        s = d / (2 - mx - mn) if l > 0.5 else d / (mx + mn)
        if mx == r:
            h = (g - b) / d + (6 if g < b else 0)
        elif mx == g:
            h = (b - r) / d + 2
        else:
            h = (r - g) / d + 4
        h /= 6
    return f"{round(h * 360)} {round(s * 100)}% {round(l * 100)}%"


def _build_globals_css(primary_data: dict | None) -> str | None:
    """Gera globals.css com tokens HSL extraidos. Retorna None se nao houver dados."""
    if not primary_data:
        return None

    body = primary_data.get("bodyStyles", {})
    bg_hsl = _rgb_to_hsl_str(body.get("backgroundColor", "")) or "0 0% 100%"
    fg_hsl = _rgb_to_hsl_str(body.get("color", "")) or "240 10% 3.9%"

    top_colors = primary_data.get("topColors", [])
    primary_hsl = "240 5.9% 10%"
    secondary_hsl = "240 4.8% 95.9%"
    accent_hsl = "240 4.8% 95.9%"
    border_hsl = "240 5.9% 90%"
    if len(top_colors) > 2:
        primary_hsl = _rgb_to_hsl_str(top_colors[1]["color"]) or primary_hsl
    if len(top_colors) > 3:
        secondary_hsl = _rgb_to_hsl_str(top_colors[2]["color"]) or secondary_hsl
    if len(top_colors) > 4:
        accent_hsl = _rgb_to_hsl_str(top_colors[3]["color"]) or accent_hsl

    return f"""@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {{
  :root {{
    --background: {bg_hsl};
    --foreground: {fg_hsl};
    --primary: {primary_hsl};
    --primary-foreground: {bg_hsl};
    --secondary: {secondary_hsl};
    --secondary-foreground: {fg_hsl};
    --muted: {secondary_hsl};
    --muted-foreground: {fg_hsl};
    --accent: {accent_hsl};
    --accent-foreground: {fg_hsl};
    --border: {border_hsl};
    --radius: 0.5rem;
  }}

  body {{
    background-color: hsl(var(--background));
    color: hsl(var(--foreground));
    font-family: {body.get("fontFamily", "system-ui, -apple-system, sans-serif")};
  }}
}}
"""


def _build_layout_tsx(meta: dict, google_fonts: list[str]) -> str:
    """Gera layout.tsx com fontes Google e meta da pagina original."""
    lang = (meta.get("lang") or "pt-BR")[:5]
    title = (meta.get("title") or "Cloned Site").replace('"', "'")[:120]
    desc = (meta.get("description") or "Generated by Clow Website Cloner").replace('"', "'")[:200]

    font_links = ""
    for href in google_fonts[:3]:
        font_links += f'        <link rel="stylesheet" href="{href}" />\n'

    return f'''import type {{ Metadata }} from "next";
import "./globals.css";

export const metadata: Metadata = {{
  title: "{title}",
  description: "{desc}",
}};

export default function RootLayout({{
  children,
}}: Readonly<{{ children: React.ReactNode }}>) {{
  return (
    <html lang="{lang}">
      <head>
{font_links}      </head>
      <body className="antialiased">{{children}}</body>
    </html>
  );
}}
'''


def run_foundation(
    template_dir: str | Path,
    output_dir: str | Path,
    recon_result: dict,
    browser=None,
    do_npm_install: bool = True,
) -> dict:
    """Copia scaffold pra output, popula globals.css/layout.tsx, baixa assets."""
    template_dir = Path(template_dir)
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    if not template_dir.exists():
        return {"status": "error", "error": f"Template nao encontrado: {template_dir}"}

    # Copia scaffold (preserva docs/research/ ja criado pelo recon)
    research_backup = output_dir / "docs"
    has_research = research_backup.exists()
    if has_research:
        tmp_backup = output_dir.parent / f"_research_backup_{output_dir.name}"
        if tmp_backup.exists():
            shutil.rmtree(tmp_backup)
        shutil.copytree(research_backup, tmp_backup)

    for item in template_dir.iterdir():
        target = output_dir / item.name
        if item.is_dir():
            if target.exists():
                shutil.rmtree(target)
            shutil.copytree(item, target)
        else:
            shutil.copy2(item, target)

    # Restaura docs/research/
    if has_research:
        if research_backup.exists():
            shutil.rmtree(research_backup)
        shutil.copytree(tmp_backup, research_backup)
        shutil.rmtree(tmp_backup)

    primary_data = recon_result.get("primary_data") or {}

    # Sobrescreve globals.css com tokens extraidos
    css = _build_globals_css(primary_data)
    if css:
        (output_dir / "src" / "app" / "globals.css").write_text(css, encoding="utf-8")

    # Sobrescreve layout.tsx com meta + fonts
    meta = primary_data.get("meta", {})
    google_fonts = primary_data.get("googleFonts", [])
    layout = _build_layout_tsx(meta, google_fonts)
    (output_dir / "src" / "app" / "layout.tsx").write_text(layout, encoding="utf-8")

    # Baixa assets (usa Browser.download_assets se browser foi passado)
    assets_info = {"downloaded": 0}
    if browser is not None:
        try:
            assets_info = browser.download_assets(str(output_dir / "public"))
        except Exception as e:
            logger.warning("download_assets falhou: %s", e)
            assets_info = {"downloaded": 0, "error": str(e)}

    # npm install (opcional)
    npm_result = {"status": "skipped"}
    if do_npm_install and has_node():
        npm_result = run_npm_install(output_dir, timeout=300)

    return {
        "status": "ok",
        "output_dir": str(output_dir),
        "globals_css_written": bool(css),
        "layout_tsx_written": True,
        "assets": assets_info,
        "npm_install": npm_result,
    }
