apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

commonLabels:
  app.kubernetes.io/name: clow
  app.kubernetes.io/part-of: clow
  app.kubernetes.io/managed-by: kustomize

namespace: clow
