"""Testes dos install tokens e proxy chat."""

import os
import sys
import time
import unittest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))


class TestInstallTokens(unittest.TestCase):

    def test_generate_token(self):
        from clow.routes.install_tokens import _generate_token
        data = _generate_token("user1", "tenant1", "starter")
        self.assertTrue(data["token"].startswith("clow_install_"))
        self.assertEqual(data["plan"], "starter")
        self.assertIn("sonnet", data["model"])
        self.assertGreater(data["expires_at"], time.time())

    def test_validate_token_valid(self):
        from clow.routes.install_tokens import _generate_token, _validate_token
        data = _generate_token("user2", "tenant2", "pro")
        result = _validate_token(data["token"])
        self.assertIsNotNone(result)
        self.assertEqual(result["plan"], "pro")
        self.assertEqual(result["user_id"], "user2")

    def test_validate_token_invalid(self):
        from clow.routes.install_tokens import _validate_token
        result = _validate_token("clow_install_fake_token_xyz")
        self.assertIsNone(result)

    def test_token_single_use(self):
        from clow.routes.install_tokens import _generate_token, _validate_token, _mark_token_used
        data = _generate_token("user3", "tenant3", "lite")
        # First validation: valid
        self.assertIsNotNone(_validate_token(data["token"]))
        # Mark as used
        _mark_token_used(data["token"])
        # Second validation: invalid (already used)
        self.assertIsNone(_validate_token(data["token"]))

    def test_token_requires_paid_plan(self):
        from clow.routes.install_tokens import PAID_PLANS
        self.assertIn("lite", PAID_PLANS)
        self.assertIn("starter", PAID_PLANS)
        self.assertIn("pro", PAID_PLANS)
        self.assertIn("business", PAID_PLANS)
        self.assertNotIn("byok_free", PAID_PLANS)
        self.assertNotIn("free", PAID_PLANS)

    def test_plan_model_mapping(self):
        from clow.routes.install_tokens import PLAN_MODELS
        self.assertIn("haiku", PLAN_MODELS["lite"])
        self.assertIn("sonnet", PLAN_MODELS["starter"])
        self.assertIn("sonnet", PLAN_MODELS["pro"])
        self.assertIn("sonnet", PLAN_MODELS["business"])

    def test_setup_script_no_api_key(self):
        """Verifica que o script de setup NAO contem a API key do servidor."""
        from clow.routes.install_tokens import _generate_token
        from clow import config
        data = _generate_token("user4", "tenant4", "starter")
        # The script would be generated by the endpoint, but we can check
        # that the token data doesn't contain the server API key
        self.assertNotIn(config.ANTHROPIC_API_KEY, data["token"])
        self.assertNotIn("sk-ant-", data["token"])

    def test_token_expiry_check(self):
        """Token com expires_at no passado deve ser invalido."""
        from clow.routes.install_tokens import _validate_token, _init_tokens_table
        from clow.database import get_db
        _init_tokens_table()
        # Insert expired token manually
        token = "clow_install_expired_test_token"
        with get_db() as db:
            db.execute(
                "INSERT OR REPLACE INTO install_tokens (token, user_id, tenant_id, plan, model, created_at, expires_at) VALUES (?,?,?,?,?,?,?)",
                (token, "u", "t", "lite", "haiku", time.time() - 100000, time.time() - 1),
            )
        self.assertIsNone(_validate_token(token))


class TestInstallPageHTML(unittest.TestCase):
    """Verifica que a pagina de instalacao nao expoe API keys."""

    def test_no_settings_api_key_reference(self):
        """Pagina nao deve mandar usuario pegar key em Settings."""
        from pathlib import Path
        html_path = Path(__file__).parent.parent / "clow" / "templates" / "install.html"
        content = html_path.read_text(encoding="utf-8")
        self.assertNotIn("Settings", content.split("install-paid")[0] if "install-paid" in content else content)

    def test_no_inline_onclick(self):
        """Pagina nao deve ter onclick inline (bloqueado pelo CSP)."""
        from pathlib import Path
        html_path = Path(__file__).parent.parent / "clow" / "templates" / "install.html"
        content = html_path.read_text(encoding="utf-8")
        self.assertNotIn('onclick="copyCode', content)
        self.assertNotIn('onclick="showTab', content)

    def test_external_js_referenced(self):
        """Pagina deve referenciar install.js externo."""
        from pathlib import Path
        html_path = Path(__file__).parent.parent / "clow" / "templates" / "install.html"
        content = html_path.read_text(encoding="utf-8")
        self.assertIn('install.js', content)

    def test_paid_section_hidden_by_default(self):
        """Secao de plano pago deve estar escondida por padrao."""
        from pathlib import Path
        html_path = Path(__file__).parent.parent / "clow" / "templates" / "install.html"
        content = html_path.read_text(encoding="utf-8")
        self.assertIn('id="install-paid" style="display:none"', content)

    def test_tab_structure_correct(self):
        """Tabs devem ter data-tab e IDs correspondentes."""
        from pathlib import Path
        html_path = Path(__file__).parent.parent / "clow" / "templates" / "install.html"
        content = html_path.read_text(encoding="utf-8")
        for tab in ["windows", "mac", "linux", "vps"]:
            self.assertIn(f'data-tab="{tab}"', content)
            self.assertIn(f'id="tab-{tab}"', content)


if __name__ == "__main__":
    unittest.main()
